### ISSUE TITLE
Reading List<dynamic> from a Json response

### ISSUE THREAD

**Issue by Ferdzzzzzzzz** [rrousselGit/freezed#173]
Hi @rrousselGit, I know this is probably more a jsonserializable problem, but since I'm using Freezed for Dataclasses I thought I'd ask here first...

I want to read in a **List** of Json Objects using Freezed (Where the List entity is freezed as well as the objects in the list). This means I need to do something like this:

`final listEntity = SomeListEntity(jsonDecode(json).map<SomeListItemEntity>((i) => SomeListItemEntity.fromJson(i)).toList()));`

Firstly - is there currently a cleaner way to do this? I can't find any better suggestions.

Secondly - if there isn't currently a better way, would it be possible to implement a generic like this?:

```
List<dynamic> fromList<T>(String json) { 
    final List<dynamic> l = jsonDecode(json);
    return l.map<T>((i) => T.fromJson(i)).toList();
}
```

Usage: `final listEntity = SomeListEntity(fromList<SomeListItemEntity>(json));`

Currently, if I try this there is an error on the `fromJson` factory: `The method 'fromJson' isn't defined for the type 'Type'.` which makes sense to me, but a workaround would be nice if you have any suggestions. The only workaround I've found is [this](https://stackoverflow.com/questions/56253103/can-i-use-generics-in-dart-like-this), which is messy to say the least.

To finish off - big thanks for Freezed and your other community work. You're killing it 🔥❄️

**Comment by rrousselGit** [comment]
In theory, json_serializable does deep deserializing out of the box.

You'll have to share a bit more about your use-case so that I understand
what is wrong.

**Comment by Ferdzzzzzzzz** [comment]
@rrousselGit I don't have a problem with deep deserializing, that works quite well actually 😄 my use case is more specifically when I get a list of objects from an API, eg: 

```
[
  {
    name: "John",
    age: 18,
  },
  {
    name: "George",
    age: 20,
  }
]
```

In that scenario, I can't use the built in `fromJson` as it expects a `Map<String, dynamic>` and receives a `List<dynamic>`.

**Comment by rrousselGit** [comment]
Make a helper like the following to help:

```dart
@freezed
abstract class Whatever with _$Whatever {
  factory Whatever(List<MyObject> data) = _Whatever;

  factory Whatever.fromJson(Map<String, dynamic> json) => _$WhateverFromJson(json);
}
```

Then do

```dart
final whatever = Whatever.fromJson({'data': [<your list>]});

final result = whatever.data;
```

**Comment by Ferdzzzzzzzz** [comment]
So simple, worked like a charm 😄 thanks man 👍

**Comment by tazik561** [comment]
> ```dart
> _Whatever
> ```

I have this json:
```
[
    {
        "word": "hello",
        "phonetics": [
            {
                "text": "/həˈloʊ/",
                "audio": "https://lex-audio.useremarkable.com/mp3/hello_us_1_rr.mp3"
            },
            {
                "text": "/hɛˈloʊ/",
                "audio": "https://lex-audio.useremarkable.com/mp3/hello_us_2_rr.mp3"
            }
        ],
        "meanings": [
            {
                "partOfSpeech": "exclamation",
                "definitions": [
                    {
                        "definition": "Used as a greeting or to begin a phone conversation.",
                        "example": "hello there, Katie!"
                    }
                ]
            },
            {
                "partOfSpeech": "noun",
                "definitions": [
                    {
                        "definition": "An utterance of “hello”; a greeting.",
                        "example": "she was getting polite nods and hellos from people",
                        "synonyms": [
                            "greeting",
                            "welcome",
                            "salutation",
                            "saluting",
                            "hailing",
                            "address",
                            "hello",
                            "hallo"
                        ]
                    }
                ]
            },
            {
                "partOfSpeech": "intransitive verb",
                "definitions": [
                    {
                        "definition": "Say or shout “hello”; greet someone.",
                        "example": "I pressed the phone button and helloed"
                    }
                ]
            }
        ]
    }
]
```
and this is my freezed :
```
import 'package:freezed_annotation/freezed_annotation.dart';
part 'vocabularies_model.freezed.dart';
part 'vocabularies_model.g.dart';

@freezed
abstract class VocabulariesModel with _$VocabulariesModel {
  const factory VocabulariesModel({
    List<VocabularyModel>? model,
  }) = _VocabulariesModel;

  factory VocabulariesModel.fromJson(Map<String, dynamic> json) =>
      _$VocabulariesModelFromJson(json);
}

@freezed
abstract class VocabularyModel with _$VocabularyModel {
  const factory VocabularyModel(
      {String? word,
      List<Phonetics>? phonetics,
      List<Meanings>? meanings}) = _VocabularyModel;

  factory VocabularyModel.fromJson(Map<String, dynamic> json) =>
      _$VocabularyModelFromJson(json);
}

@freezed
abstract class Phonetics with _$Phonetics {
  const factory Phonetics({
    String? text,
    String? audio,
  }) = _Phonetics;
  factory Phonetics.fromJson(Map<String, dynamic> json) =>
      _$PhoneticsFromJson(json);
}

@freezed
abstract class Meanings with _$Meanings {
  const factory Meanings({
    String? partOfSpeech,
    List<Definitions>? definitions,
  }) = _Meanings;

  factory Meanings.fromJson(Map<String, dynamic> json) =>
      _$MeaningsFromJson(json);
}

@freezed
abstract class Definitions with _$Definitions {
  const factory Definitions(
      {String? definition,
      String? example,
      List<String>? synonyms}) = _Definitions;
  factory Definitions.fromJson(Map<String, dynamic> json) =>
      _$DefinitionsFromJson(json);
}
```

but I got this error:
```
⛔ DioError [DioErrorType.other]: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>?'
I/flutter ( 6065): │ ⛔ #0      DioMixin.assureResponse (package:dio/src/dio_mixin.dart:832:10)
I/flutter ( 6065): │ ⛔ #1      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:605:14)
I/flutter ( 6065): │ ⛔ #2      _rootRunUnary (dart:async/zone.dart:1362:47)
I/flutter ( 6065): │ ⛔ #3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
I/flutter ( 6065): │ ⛔ <asynchronous suspension>
I/flutter ( 6065): │ ⛔ #4      _RestClient.getVocabulary (package:english_vocabulary_builder/app/services/rest_client.g.dart:21:21)
I/flutter ( 6065): │ ⛔ <asynchronous suspension>
I/flutter ( 6065): │ ⛔ #5      AddRemoteDataSource.getVocabulary (package:english_vocabulary_builder/feautures/home/data/data_source/add_remote_data_source.dart:12:24)
I/flutter ( 6065): │ ⛔ <asynchronous suspension>
I/flutter ( 6065): │ ⛔ #6      AddController.showAddDialog (package:english_vocabulary_builder/feautures/home/presentation/controller/add_controller.dart:26:23)
I/flutter ( 6065): │ ⛔ <asynchronous suspension>
I/flutter ( 6065): │ ⛔ 
```

Why I can't get right answer?

**Comment by MartychDenys** [comment]
@freezed
class UsersResponseModel with _$UsersResponseModel {
  const factory UsersResponseModel({
    required List<UserEntyti> users,
  }) = _UsersResponseModel;

  factory UsersResponseModel.fromList(List<dynamic> list) {
    return UsersResponseModel(
      users: list
          .map((e) => UserEntyti.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }
}
