### ISSUE TITLE
freezed build_runner error

### ISSUE THREAD

**Issue by Patrick386** [rrousselGit/freezed#656]
A problem suddenly occurred.
I don't know what the problem is.

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter        
  freezed_annotation: any
  json_annotation: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: any
  freezed: any
  json_serializable: any
```

```
Invalid argument(s): Missing library: package:pronto/models/product//product_data.dart
Available libraries: [dart:typed_data, dart:convert, dart:math, dart:core, dart:_internal, dart:collection, dart:async, dart:isolate, dart:developer, dart:ffi, dart:_js_embedded_names, dart:_js_names, dart:_recipe_syntax, dart:_rti, dart:_foreign_helper, dart:_js_helper, dart:_interceptors, dart:_native_typed_data, dart:web_gl, dart:js_util, dart:_metadata, dart:html_common, dart:indexed_db, dart:svg, dart:web_audio, dart:html, dart:io, dart:_http, dart:js, dart:_js, dart:mirrors, dart:nativewrappers, dart:cli, dart:_late_helper, dart:_dart2js_runtime_metrics, dart:_js_primitives, dart:_async_await_error_codes, dart:_js_annotations, dart:_spirv, dart:ui]
#0      LinkedElementFactory.createLibraryElementForReading (package:analyzer/src/summary2/linked_element_factory.dart:74:7)
#1      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:128:14)
#2      LinkedElementFactory.libraryOfUri (package:analyzer/src/summary2/linked_element_factory.dart:177:12)
#3      ElementBuilder._selectLibrary (package:analyzer/src/summary2/element_builder.dart:1018:37)
#4      ElementBuilder.visitImportDirective (package:analyzer/src/summary2/element_builder.dart:598:31)
#5      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5953:50)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7758:20)
#7      ElementBuilder.buildLibraryElementChildren (package:analyzer/src/summary2/element_builder.dart:60:21)
#8      LibraryBuilder.buildElements (package:analyzer/src/summary2/library_builder.dart:109:24)
#9      Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:109:15)
#10     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:88:5)
#11     Linker.link (package:analyzer/src/summary2/link.dart:74:5)
#12     link (package:analyzer/src/summary2/link.dart:33:10)
#13     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:176:30)
#14     SetMixin.forEach (dart:collection/set.dart:142:30)
#15     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:113:32)
#16     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:206:7)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#18     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:204:12)
#19     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1574:22)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#21     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1572:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1126:35)
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:24)
<asynchronous suspension>


[INFO] 24.5s elapsed, 53/69 actions completed.
[INFO] 25.6s elapsed, 53/69 actions completed.
[INFO] 26.7s elapsed, 53/69 actions completed.
[INFO] 27.7s elapsed, 53/69 actions completed.
[INFO] 28.8s elapsed, 53/69 actions completed.
```

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale ko-KR)
    • Flutter version 2.10.5 at /Users/patrick386/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (9 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by rrousselGit** [comment]
> Invalid argument(s): Missing library: package:pronto/models/product//product_data.dart


It sounds like there's a problem in your product_data.dart file

**Comment by Patrick386** [comment]
I don't know the exact cause, but the problem has been resolved.

First I removed **build_verify** .
Then split the model into independent files.

Referenced file paths have been clarified.
Example:> import: '../../models/product.dart'
-> import: 'package:useProject/models/product.dart'

and,

@Default([])
List<otherModel> aaa,
---> List<otherModel>? aaa,
