### ISSUE TITLE
(With reproducible repository) Cannot run build runner for freezed: `Asset [....freezed.dart] is not a Dart library. It may be a part file or a file without Dart source code.`

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/freezed#668]
Hi thanks for the repo! However I am facing a bug that makes it impossible to use this library.

Steps: Download https://github.com/fzyzcjy/freezed_build_runner_bug. Run `flutter pub get`. Run `flutter pub run build_runner build --delete-conflicting-outputs --verbose`.

Output:

```shell
...
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +82 ms] executing: /Users/tom/fvm/versions/3.0.0/bin/cache/dart-sdk/bin/dart __deprecated_pub run build_runner build
--delete-conflicting-outputs --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 497ms

[WARNING] ApplyBuilders:
Configuring `mobx_codegen:mobx_generator` in target `freezed_build_runner_bug:freezed_build_runner_bug` but this is not a known Builder
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 54ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 556ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 23ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 29ms

[SEVERE] source_gen:combining_builder on lib/src/model/a.freezed.dart (cached):

Asset [freezed_build_runner_bug|lib/src/model/a.freezed.dart] is not a Dart library. It may be a part file or a file without Dart source code.
package:build_resolvers/src/resolver.dart 222:7   AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 123:26  PerActionResolver.libraryFor.<fn>
package:source_gen/builder.dart 115:26            CombiningBuilder.build

[SEVERE] Build:
Failed after 89ms
[+2957 ms] "flutter run" took 3,124ms.
[   +5 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:416:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:251:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +261 ms] ensureAnalyticsSent: 258ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by vadrian89** [comment]
Hello, I seem to be having the same issue.
For me this is happening inside a dart package I made.
```

[  +52 ms] executing: /home/adrian/Programe/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub run build_runner build --delete-conflicting-outputs --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 313ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 61ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 632ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 17ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 35ms

[SEVERE] source_gen:combining_builder on lib/src/domain/core/user_model.freezed.dart (cached):

Asset [bloc_firebase_auth|lib/src/domain/core/user_model.freezed.dart] is not a Dart library. It may be a part file or a file without Dart source code.
package:build_resolvers/src/resolver.dart 222:7   AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 123:26  PerActionResolver.libraryFor.<fn>
package:source_gen/builder.dart 115:26            CombiningBuilder.build

[SEVERE] Build:
Failed after 80ms
[+2430 ms] "flutter run" took 2.542ms.
[   +6 ms] pub finished with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:416:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:251:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +177 ms] ensureAnalyticsSent: 175ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
```

```
[✓] Flutter (Channel stable, 2.10.5, on Ubuntu 20.04.4 LTS 5.13.0-41-generic, locale ro_RO.UTF-8)
    • Flutter version 2.10.5 at /home/adrian/Programe/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /home/adrian/Android/Sdk
    • Platform android-31, build-tools 33.0.0-rc1
    • ANDROID_SDK_ROOT = /home/adrian/Android/Sdk
    • Java binary at: /home/adrian/Programe/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/adrian/Programe/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The funny thing is it:
- it didn't worked at first then I added explicit library user_model; at the top of the file, then it worked;
- now all of the sudden, it doesn't want to work anymore;

Normal Flutter app projects do not have this issue.

**Comment by fzyzcjy** [comment]
@vadrian89 Did you find the solution?

**Comment by vadrian89** [comment]
@fzyzcjy 
Nothing so far seems to work, so I took a break from the project for today. Thinking of downgrading packages to see if they work.

**Comment by fzyzcjy** [comment]
Possibly due to https://github.com/dart-lang/sdk/issues/49031 ?

**Comment by jakemac53** [comment]
Yes this should be fixed by upgrading to the latest analyzer version (specifically, `4.1.0`)

**Comment by rrousselGit** [comment]
Awesome, thanks for the fix!

**Comment by digu3120** [comment]
👉 Try it out now: https://dartfreezed.tech/

 💬 I’d love your feedback and suggestions!

🚀 Introducing dartfreezed.tech – Your AI-Powered Flutter Freezed Model Generator! ⚡

Tired of manually converting complex JSON into Dart models?

 Say hello to dartfreezed.tech – a smart, lightning-fast tool that uses AI to generate Freezed and JsonSerializable Dart models from any JSON response in seconds!

 ✅ Powered by AI for intelligent field detection

 ✅ Clean, reliable Freezed models with built-in null safety

 ✅ Boosts productivity for Flutter developers

 ✅ Handles deeply nested and complex structures with ease
