### ISSUE TITLE
Unsupported operation: Cannot add to an unmodifiable list when makeCollectionsUnmodifiable: false

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/freezed#693]
I added `makeCollectionsUnmodifiable: false` but still got error

```
E/flutter ( 4802): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Unsupported operation: Cannot add to an unmodifiable list
E/flutter ( 4802): #0      UnmodifiableListMixin.add (dart:_internal/list.dart:114:5)
E/flutter ( 4802): #1      _AddAccountScreenState.build.<anonymous closure> (package:picture_match/src/screen/add_account_screen.dart:56:33)
E/flutter ( 4802): <asynchronous suspension>
```

model:
```dart
@Freezed(makeCollectionsUnmodifiable: false)
class Data with _$Data {
  @JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
  const factory Data({
    @Default([]) List<Account> accounts,
  }) = _Data;

  factory Data.fromJson(Map<String, dynamic> json) => _$DataFromJson(json);
}
```

version: 
freezed_annotation: ^2.0.3
freezed: ^2.0.3+1

**Comment by rrousselGit** [comment]
Could you maybe add a complete example? Your stacktrace points to code that isn't in what you gave

**Comment by tbm98** [comment]
my minimal example:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'main.freezed.dart';
part 'main.g.dart';

@Freezed(makeCollectionsUnmodifiable: false)
class A with _$A {
  @JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
  const factory A({
    @Default([]) List<String> list,
  }) = _A;

  factory A.fromJson(Map<String, dynamic> json) => _$AFromJson(json);
}

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: TextButton(
              onPressed: () {
                final a = A();
                a.list.add('value');
                print(a.list);
              },
              child: Text('Hello World')),
        ),
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
Oh, it's unrelated to the immutable collection flag.
You used the default value, which is a constant


Constant lists aren't mutable.

**Comment by tbm98** [comment]
did you mean immutable collection flag only works with fields that don't have a default value?

**Comment by rrousselGit** [comment]
No

It's just that while Freezed doesn't make the list immutable, the value _you_ passed is immutable

You did:

```dart
var list = const [];

list.add(42);
```

**Comment by tbm98** [comment]
I got it. Thanks!
