### ISSUE TITLE
Could not resolve annotation for `Type override`

### ISSUE THREAD

**Issue by SilverMira** [rrousselGit/freezed#832]
**Describe the bug**
Source gen fails if the freezed class contains a property named `override`. The error says it's from `json_serializable` but it doesn't happen when using either `freezed` or `json_serializable` on their own, it only happens when `freezed` is used together with `json_serializable`.

<details>
<summary>flutter pub run build_runner build --verbose</summary>

```
[SEVERE] json_serializable on test.dart (cached):

Could not resolve annotation for `String override`.
package:source_gen/src/type_checker.dart 114:7              TypeChecker._computeConstantValue
package:source_gen/src/type_checker.dart 139:21             TypeChecker._annotationsWhere
dart:core                                                   Iterable.isEmpty
package:source_gen/src/type_checker.dart 73:20              TypeChecker.firstAnnotationOf
package:json_serializable/src/utils.dart 17:21              _jsonKeyAnnotation
package:json_serializable/src/utils.dart 27:5               hasJsonKeyAnnotation
dart:collection                                             ListMixin.firstWhere
package:json_serializable/src/field_helpers.dart 30:16      new _FieldSet
package:json_serializable/src/field_helpers.dart 103:19     createSortedFieldSet.<fn>
dart:core                                                   Iterable.toList
package:json_serializable/src/field_helpers.dart 104:8      createSortedFieldSet
package:json_serializable/src/generator_helper.dart 54:26   GeneratorHelper.generate
dart:_internal                                              WhereIterator.moveNext
package:json_serializable/src/json_part_builder.dart 64:27  _UnifiedGenerator.generate
package:source_gen/src/builder.dart 352:23                  _generate

[SEVERE] Build:
Failed after 82ms
[+2699 ms] "flutter run" took 2,832ms.
[   +6 ms] pub finished with exit code 1
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:418:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:249:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

```

</details>

**To Reproduce**

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test.g.dart';
part 'test.freezed.dart';

@freezed()
class Test {

  factory Test({required String override}) = _Test;

  factory Test.fromJson(Map<String, dynamic> json) => _$TestFromJson(json);

  Map<String, dynamic> toJson() => _$TestToJson(this);
}

```

**Expected behavior**
Source gen should be successful

**Comment by rrousselGit** [comment]
Using "override" as a variable name is probably a bit problematic.

Because that name is also used for the `@override` annotation.

**Comment by SilverMira** [comment]
I do get why its problematic, but `override` is a perfectly acceptable property / variable name elsewhere. The fact that it only fails when generating `json_serializable` methods with `freezed` class but not when either one is used standalone suggests the integration of both packages part of the source gen has an issue?
